'use strict';
// ScenarioLoader: loads scenario .json files into the game.
//
//   - on start: `?scenario=<url>` or scenarios/bunker-compound.json, fetched over HTTP. Opened from disk,
//     browsers block fetch() on file:// URLs, so the embedded copy (scenarios/<name>.js, generated by
//     tools/embed-scenarios.mjs) is used instead; with neither, a panel asks for the file
//   - any time: the "Load scenario" button, key L, or drop a .json file on the page

class ScenarioLoader {
    constructor(game) {
        this.game = game;
        this.panel = document.getElementById('loader');
        this.input = document.getElementById('loader-file');
        this.message = document.getElementById('loader-message');
    }

    static get DEFAULT_URL() { return 'scenarios/bunker-compound.json'; }

    get initialUrl() {
        return new URLSearchParams(location.search).get('scenario') || ScenarioLoader.DEFAULT_URL;
    }

    attach() {
        document.addEventListener('dragover', e => e.preventDefault());
        document.addEventListener('drop', e => {
            e.preventDefault();
            const file = e.dataTransfer.files[0];
            if (file) this.loadFile(file);
        });
        this.input.addEventListener('change', () => {
            if (this.input.files[0]) this.loadFile(this.input.files[0]);
            this.input.value = '';          // picking the same file again still fires `change`
        });
        document.getElementById('load-button').addEventListener('click', () => this.pick());
    }

    // open the file picker (button, key L)
    pick() {
        if (document.pointerLockElement) document.exitPointerLock();
        this.input.click();
    }

    // fetch the initial scenario, or use its embedded copy; errors in the data itself propagate (they are
    // fatal on start)
    async loadInitial() {
        const url = this.initialUrl, embedded = (window.EMBEDDED_SCENARIOS || {})[url];
        let scn;
        try {
            const res = await fetch(url);
            if (!res.ok) throw new Error(`HTTP ${res.status}`);
            scn = await res.json();
        } catch (err) {
            if (embedded) scn = embedded;
            else {
                this.ask(`Could not fetch "${url}" (${err.message}).` +
                    (location.protocol === 'file:' ? ' Browsers block fetch() on pages opened from disk: serve the folder over HTTP, or pick the file here.' : ''));
                return;
            }
        }
        this.game.load(scn);
    }

    async loadFile(file) {
        try {
            this.game.load(JSON.parse(await file.text()));
            this.panel.classList.remove('show');
        } catch (err) {
            console.error(err);
            if (this.game.world) this.game.hud.toast('Scenario error: ' + err.message);
            else this.ask(`"${file.name}": ${err.message}`);
        }
    }

    ask(msg) {
        this.message.textContent = msg;
        this.panel.classList.add('show');
    }
}
